-- Create the Notification table.
-- This must run before notification_read_receipts and notification_email_dispatch
-- which add foreign keys referencing this table.

-- Enum
DO $$ BEGIN CREATE TYPE "NotificationType" AS ENUM ('POLICY_CREATED','POLICY_UPDATED','POLICY_ARCHIVED','ANNOUNCEMENT','SYSTEM','PROFILE_INCOMPLETE','REVIEW_SUBMITTED','REVIEW_ACKNOWLEDGED','DISCIPLINARY_CREATED','DISCIPLINARY_UPDATED','HIERARCHY_CHANGED','STANDING_CHANGED','VIOLATION_PENDING_HR','VIOLATION_PENDING_ADMIN','VIOLATION_APPROVED','VIOLATION_REJECTED','VIOLATION_ACKNOWLEDGED','REVIEW_PENDING_HR','REVIEW_PENDING_ADMIN','REVIEW_APPROVED','REVIEW_REJECTED','APPEAL_PENDING_HR','APPEAL_PENDING_ADMIN','APPEAL_DECIDED','LEAVE_REQUESTED','LEAVE_PENDING_HR','LEAVE_PENDING_SUPER_ADMIN','LEAVE_APPROVED','LEAVE_REJECTED','LEAVE_CANCELLED','RESOURCE_CREATED','QUARTERLY_REVIEW_CREATED','QUARTERLY_REVIEW_REMINDER','QUARTERLY_REVIEW_OVERDUE','QUARTERLY_REVIEW_ESCALATED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Table
CREATE TABLE IF NOT EXISTS "Notification" (
  "id" TEXT NOT NULL,
  "type" "NotificationType" NOT NULL,
  "title" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "link" TEXT,
  "employeeId" TEXT,
  "relatedId" TEXT,
  "relatedType" TEXT,
  "isRead" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "Notification_type_idx" ON "Notification"("type");
CREATE INDEX IF NOT EXISTS "Notification_isRead_idx" ON "Notification"("isRead");
CREATE INDEX IF NOT EXISTS "Notification_createdAt_idx" ON "Notification"("createdAt");
CREATE INDEX IF NOT EXISTS "Notification_employeeId_idx" ON "Notification"("employeeId");

DO $$ BEGIN ALTER TABLE "Notification" ADD CONSTRAINT "Notification_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
