import { Prisma } from '@targon/prisma-talos'

export const skuResponseSelect = {
  id: true,
  skuCode: true,
  skuGroup: true,
  asin: true,
  category: true,
  subcategory: true,
  sizeTier: true,
  referralFeePercent: true,
  amazonCategory: true,
  amazonSubcategory: true,
  amazonSizeTier: true,
  amazonReferralFeePercent: true,
  amazonListingPrice: true,
  amazonReferenceWeightKg: true,
  description: true,
  packSize: true,
  defaultSupplierId: true,
  secondarySupplierId: true,
  material: true,
  unitDimensionsCm: true,
  unitSide1Cm: true,
  unitSide2Cm: true,
  unitSide3Cm: true,
  unitWeightKg: true,
  itemDimensionsCm: true,
  itemSide1Cm: true,
  itemSide2Cm: true,
  itemSide3Cm: true,
  itemWeightKg: true,
  amazonItemPackageDimensionsCm: true,
  amazonItemPackageSide1Cm: true,
  amazonItemPackageSide2Cm: true,
  amazonItemPackageSide3Cm: true,
  amazonItemDimensionsCm: true,
  amazonItemSide1Cm: true,
  amazonItemSide2Cm: true,
  amazonItemSide3Cm: true,
  amazonItemWeightKg: true,
  unitsPerCarton: true,
  cartonDimensionsCm: true,
  cartonSide1Cm: true,
  cartonSide2Cm: true,
  cartonSide3Cm: true,
  cartonWeightKg: true,
  packagingType: true,
  isActive: true,
  createdAt: true,
  updatedAt: true,
  fbaStock: true,
  fbaStockLastUpdated: true,
} satisfies Prisma.SkuSelect

export type SkuResponseRow = Prisma.SkuGetPayload<{
  select: typeof skuResponseSelect
}>
