import test from 'node:test'
import assert from 'node:assert/strict'
import { createCompareViewModel } from './compare-view-model'
import type { WprBenchmarkCompetitor, WprBusinessReportsWindow, WprCluster, WprCompetitorSummary, WprScpWindow, WprWeekBundle } from './types'

function buildCompetitor(): WprBenchmarkCompetitor {
  return {
    identity: { brand: 'Competitor', asin: 'B000TEST', config_source: 'config' },
    coverage: {
      weeks_keywords_recent_4w: 0,
      weeks_keywords_baseline_13w: 0,
      recent_rank_coverage_strength: 'none',
      benchmark_available: false,
    },
    raw_input: {
      recent_4w: { weeks_present: [], weeks_keywords: 0, avg_rank: null, best_rank: null, visibility_est: null },
      baseline_13w: { weeks_present: [], weeks_keywords: 0, avg_rank: null, best_rank: null, visibility_est: null },
    },
    estimated_output: {
      recent_4w: { visibility_est: null },
      baseline_13w: { visibility_est: null },
    },
    gap_to_target: { rank_recent_4w: null, rank_best_recent_4w: null, rank_baseline_13w: null },
    benchmark_available: false,
  }
}

function buildCompetitorSummary(): WprCompetitorSummary {
  return { brand: 'Competitor', asin: 'B000TEST', config_source: 'config' }
}

function buildCluster(id: string, cluster: string, queryVolume: number, avgRank: number | null): WprCluster {
  const competitor = buildCompetitor()
  return {
    id,
    cluster,
    family: 'Family',
    core: true,
    terms_count: 1,
    search_volume: queryVolume,
    query_volume: queryVolume,
    market_impressions: 1000,
    asin_impressions: 200,
    market_clicks: 300,
    asin_clicks: 60,
    market_cart_adds: 100,
    asin_cart_adds: 20,
    market_purchases: 50,
    asin_purchases: 12,
    market_ctr: 0.3,
    market_cvr: 0.16,
    asin_ctr: 0.3,
    asin_cvr: 0.2,
    impression_share: 0.2,
    click_share: 0.2,
    cart_add_rate: 0.33,
    asin_cart_add_rate: 0.33,
    cart_add_share: 0.2,
    purchase_share: 0.24,
    avg_rank: avgRank,
    rank_change: -1,
    rank_gap: -2,
    rank_volatility: 1.5,
    rank_weeks: 2,
    weeks_covered: 2,
    ppc_clicks: 15,
    ppc_spend: id === 'cluster-1' ? 40 : 20,
    ppc_sales: id === 'cluster-1' ? 120 : 60,
    ppc_acos: 0.33,
    ppc_cvr: 0.2,
    expected_rank: avgRank,
    top_terms: ['term'],
    weekly: [
      {
        week_label: 'W15',
        week_number: 15,
        start_date: '2026-04-05',
        market_impressions: 1000,
        asin_impressions: 200,
        market_clicks: 300,
        asin_clicks: 60,
        market_cart_adds: 100,
        asin_cart_adds: 20,
        market_purchases: 50,
        asin_purchases: 12,
        query_volume: queryVolume - 10,
        ppc_impressions: 200,
        ppc_clicks: 15,
        ppc_spend: 20,
        ppc_sales: 60,
        ppc_orders: 4,
        rank_weight: 1,
        rank_sum: avgRank ?? 0,
        rank_span_sum: 1,
        rank_term_count: 1,
        rank_weeks: avgRank === null ? 0 : 1,
        weeks_in_window: 1,
        avg_rank: avgRank,
        rank_volatility: 1,
        market_ctr: 0.3,
        market_cvr: 0.16,
        asin_ctr: 0.3,
        asin_cvr: 0.2,
        impression_share: 0.2,
        click_share: 0.2,
        cart_add_rate: 0.33,
        asin_cart_add_rate: 0.33,
        cart_add_share: 0.2,
        purchase_share: 0.24,
        ppc_acos: 0.33,
        ppc_cvr: 0.2,
      },
      {
        week_label: 'W16',
        week_number: 16,
        start_date: '2026-04-12',
        market_impressions: 1100,
        asin_impressions: 220,
        market_clicks: 320,
        asin_clicks: 66,
        market_cart_adds: 110,
        asin_cart_adds: 24,
        market_purchases: 55,
        asin_purchases: 14,
        query_volume: queryVolume,
        ppc_impressions: 210,
        ppc_clicks: 16,
        ppc_spend: 25,
        ppc_sales: 70,
        ppc_orders: 5,
        rank_weight: 1,
        rank_sum: avgRank ?? 0,
        rank_span_sum: 1,
        rank_term_count: 1,
        rank_weeks: avgRank === null ? 0 : 1,
        weeks_in_window: 1,
        avg_rank: avgRank,
        rank_volatility: 1,
        market_ctr: 0.29,
        market_cvr: 0.17,
        asin_ctr: 0.3,
        asin_cvr: 0.21,
        impression_share: 0.2,
        click_share: 0.2,
        cart_add_rate: 0.34,
        asin_cart_add_rate: 0.36,
        cart_add_share: 0.22,
        purchase_share: 0.25,
        ppc_acos: 0.35,
        ppc_cvr: 0.22,
      },
    ],
    coverage: {
      weeks_sqp: 0,
      weeks_rank: avgRank === null ? 0 : 2,
      weeks_ppc: 2,
      recent_4w: { weeks_sqp: 0, weeks_rank: avgRank === null ? 0 : 2, weeks_ppc: 2 },
      baseline_to_anchor: { weeks_sqp: 0, weeks_rank: avgRank === null ? 0 : 2, weeks_ppc: 2 },
    },
    eligibility: { rank_eligible: avgRank !== null },
    observed: {
      current_week: {
        week_label: 'W16',
        week_number: 16,
        start_date: '2026-04-12',
        market_impressions: 0,
        asin_impressions: 0,
        market_clicks: 0,
        asin_clicks: 0,
        market_cart_adds: 0,
        asin_cart_adds: 0,
        market_purchases: 0,
        asin_purchases: 0,
        query_volume: 0,
        ppc_impressions: 0,
        ppc_clicks: 0,
        ppc_spend: 0,
        ppc_sales: 0,
        ppc_orders: 0,
        rank_weight: 0,
        rank_sum: 0,
        rank_span_sum: 0,
        rank_term_count: 0,
        rank_weeks: 0,
        weeks_in_window: 0,
        avg_rank: null,
        rank_volatility: null,
        market_ctr: 0,
        market_cvr: 0,
        asin_ctr: 0,
        asin_cvr: 0,
        impression_share: 0,
        click_share: 0,
        cart_add_rate: 0,
        asin_cart_add_rate: 0,
        cart_add_share: 0,
        purchase_share: 0,
        ppc_acos: 0,
        ppc_cvr: 0,
      },
      recent_4w: {
        week_label: 'W16',
        week_number: 16,
        start_date: '2026-04-12',
        market_impressions: 0,
        asin_impressions: 0,
        market_clicks: 0,
        asin_clicks: 0,
        market_cart_adds: 0,
        asin_cart_adds: 0,
        market_purchases: 0,
        asin_purchases: 0,
        query_volume: 0,
        ppc_impressions: 0,
        ppc_clicks: 0,
        ppc_spend: 0,
        ppc_sales: 0,
        ppc_orders: 0,
        rank_weight: 0,
        rank_sum: 0,
        rank_span_sum: 0,
        rank_term_count: 0,
        rank_weeks: 0,
        weeks_in_window: 0,
        avg_rank: null,
        rank_volatility: null,
        market_ctr: 0,
        market_cvr: 0,
        asin_ctr: 0,
        asin_cvr: 0,
        impression_share: 0,
        click_share: 0,
        cart_add_rate: 0,
        asin_cart_add_rate: 0,
        cart_add_share: 0,
        purchase_share: 0,
        ppc_acos: 0,
        ppc_cvr: 0,
      },
      baseline_13w: {
        week_label: 'W16',
        week_number: 16,
        start_date: '2026-04-12',
        market_impressions: 0,
        asin_impressions: 0,
        market_clicks: 0,
        asin_clicks: 0,
        market_cart_adds: 0,
        asin_cart_adds: 0,
        market_purchases: 0,
        asin_purchases: 0,
        query_volume: 0,
        ppc_impressions: 0,
        ppc_clicks: 0,
        ppc_spend: 0,
        ppc_sales: 0,
        ppc_orders: 0,
        rank_weight: 0,
        rank_sum: 0,
        rank_span_sum: 0,
        rank_term_count: 0,
        rank_weeks: 0,
        weeks_in_window: 0,
        avg_rank: null,
        rank_volatility: null,
        market_ctr: 0,
        market_cvr: 0,
        asin_ctr: 0,
        asin_cvr: 0,
        impression_share: 0,
        click_share: 0,
        cart_add_rate: 0,
        asin_cart_add_rate: 0,
        cart_add_share: 0,
        purchase_share: 0,
        ppc_acos: 0,
        ppc_cvr: 0,
      },
    },
    benchmark: { competitor },
    tstCompare: {
      recent_4w: {
        source: 'TST',
        method: 'observed_top_clicked_asin_pool',
        coverage: { terms_total: 1, terms_covered: 1, weeks_present: 2, term_weeks_covered: 2, avg_click_pool_share: 0.2, avg_purchase_pool_share: 0.18 },
        observed: {
          total_click_pool_share: 0.4,
          total_purchase_pool_share: 0.36,
          our_click_share_points: 0.08,
          our_purchase_share_points: 0.09,
          competitor_click_share_points: 0.12,
          competitor_purchase_share_points: 0.11,
          other_click_share_points: 0.2,
          other_purchase_share_points: 0.16,
          our_click_share: 0.2,
          our_purchase_share: 0.25,
          competitor_click_share: 0.3,
          competitor_purchase_share: 0.31,
          other_click_share: 0.5,
          other_purchase_share: 0.44,
          click_gap: -0.1,
          purchase_gap: -0.06,
        },
        term_rows: [],
        top_terms: [],
      },
      baseline_13w: {
        source: 'TST',
        method: 'observed_top_clicked_asin_pool',
        coverage: { terms_total: 1, terms_covered: 1, weeks_present: 2, term_weeks_covered: 2, avg_click_pool_share: 0.2, avg_purchase_pool_share: 0.18 },
        observed: {
          total_click_pool_share: 0.4,
          total_purchase_pool_share: 0.36,
          our_click_share_points: 0.08,
          our_purchase_share_points: 0.09,
          competitor_click_share_points: 0.12,
          competitor_purchase_share_points: 0.11,
          other_click_share_points: 0.2,
          other_purchase_share_points: 0.16,
          our_click_share: 0.2,
          our_purchase_share: 0.25,
          competitor_click_share: 0.3,
          competitor_purchase_share: 0.31,
          other_click_share: 0.5,
          other_purchase_share: 0.44,
          click_gap: -0.1,
          purchase_gap: -0.06,
        },
        term_rows: [],
        top_terms: [],
      },
      competitor: buildCompetitorSummary(),
      weekly: [],
    },
  }
}

function buildScpWindow(): WprScpWindow {
  return {
    meta: {
      targetAsin: 'B000TEST',
      recentWindow: ['W15', 'W16'],
      baselineWindow: ['W15', 'W16'],
    },
    current_week: {
      asin_count: 0,
      impressions: 0,
      clicks: 0,
      cart_adds: 0,
      purchases: 0,
      sales: 0,
      ctr: 0,
      atc_rate: 0,
      purchase_rate: 0,
      cvr: 0,
    },
    recent_4w: {
      asin_count: 0,
      impressions: 0,
      clicks: 0,
      cart_adds: 0,
      purchases: 0,
      sales: 0,
      ctr: 0,
      atc_rate: 0,
      purchase_rate: 0,
      cvr: 0,
    },
    baseline_to_anchor: {
      asin_count: 0,
      impressions: 0,
      clicks: 0,
      cart_adds: 0,
      purchases: 0,
      sales: 0,
      ctr: 0,
      atc_rate: 0,
      purchase_rate: 0,
      cvr: 0,
    },
    weekly: [],
    asins: [],
  }
}

function buildBusinessReportsWindow(): WprBusinessReportsWindow {
  return {
    meta: {
      targetAsin: 'B000TEST',
      selectedWeek: 'W16',
      availableWeeks: ['W15', 'W16'],
    },
    current_week: {
      asin_count: 0,
      sessions: 0,
      page_views: 0,
      order_items: 0,
      units_ordered: 0,
      sales: 0,
      order_item_session_percentage: 0,
      unit_session_percentage: 0,
      buy_box_percentage: 0,
    },
    baseline_to_anchor: {
      asin_count: 0,
      sessions: 0,
      page_views: 0,
      order_items: 0,
      units_ordered: 0,
      sales: 0,
      order_item_session_percentage: 0,
      unit_session_percentage: 0,
      buy_box_percentage: 0,
    },
    weekly: [],
    dailyByWeek: {},
    asins: [],
  }
}

function buildBundle(): WprWeekBundle {
  return {
    meta: {
      anchorWeek: 'W16',
      competitorBrand: 'Competitor',
      competitorAsin: 'B000TEST',
      benchmarkPolicy: 'context_only',
      competitor: { brand: 'Competitor', asin: 'B000TEST', config_source: 'config' },
      recentWindow: ['W15', 'W16'],
      baselineWindow: ['W15', 'W16'],
      policy: {
        primary_window: 'selected_week',
        baseline_window: 'baseline_13w',
        term_truth_set: 'sqp_backed_only',
        dashboard_policy: 'raw_first',
        benchmark_policy: 'context_only',
      },
    },
    weeks: ['W15', 'W16'],
    clusters: [
      buildCluster('cluster-1', 'Root One', 120, 8),
      buildCluster('cluster-2', 'Root Two', 80, 12),
    ],
    scatterClusterIds: ['cluster-1', 'cluster-2'],
    lineClusterIds: ['cluster-1', 'cluster-2'],
    shareClusterIds: ['cluster-1'],
    ppcClusterIds: ['cluster-1', 'cluster-2'],
    defaultClusterIds: ['cluster-1'],
    sqpTerms: [],
    sqpClusterTerms: {},
    sqpGlobalTermIds: [],
    regression: { slope: 0, intercept: 0 },
    brandMetrics: {
      W15: { awareness: 100, consideration: 80, purchase: 40 },
      W16: { awareness: 110, consideration: 82, purchase: 44 },
    },
    brandMetricsWindow: {
      W15: { awareness: 100, consideration: 80, purchase: 40 },
      W16: { awareness: 110, consideration: 82, purchase: 44 },
    },
    competitorWeekly: [],
    scp: buildScpWindow(),
    businessReports: buildBusinessReportsWindow(),
  }
}

test('createCompareViewModel follows the bundle id lists used by the HTML compare tab', () => {
  const vm = createCompareViewModel(buildBundle())

  assert.deepEqual(vm.scatterRows.map((row) => row.id), ['cluster-1', 'cluster-2'])
  assert.equal(vm.rankRows[0]?.weekLabel, 'W15')
  assert.equal(vm.ppcRows.length, 2)
  assert.equal(vm.brandRows[1]?.purchase, 44)
})
