export const ERD_V9_ENTITY_COLUMNS = {
  sku: [
    'sku_id',
    'sku_code',
    'sku_group',
    'asin',
    'description',
    'is_active',
    'default_supplier_id',
    'secondary_supplier_id',
    'ref_pkg_length_in',
    'ref_pkg_width_in',
    'ref_pkg_height_in',
    'ref_pkg_weight_lb',
    'ref_item_length_in',
    'ref_item_width_in',
    'ref_item_height_in',
    'ref_item_weight_lb',
    'amz_pkg_length_in',
    'amz_pkg_width_in',
    'amz_pkg_height_in',
    'amz_pkg_weight_lb',
    'amz_item_length_in',
    'amz_item_width_in',
    'amz_item_height_in',
    'amz_item_weight_lb',
    'category',
    'subcategory',
    'size_tier',
    'referral_fee_pct',
    'fba_fulfillment_fee',
  ],
  supplier: [
    'supplier_id',
    'name',
    'contact_name',
    'email',
    'phone',
    'address',
    'banking_info',
    'notes',
    'default_payment_terms',
    'default_incoterms',
  ],
  warehouse: ['warehouse_id', 'code', 'name', 'type', 'address', 'phone'],
  lot: [
    'po_id',
    'sku_id',
    'lot_ref',
    'qty_units',
    'units_per_carton',
    'cartons',
    'unit_cost',
    'pi_ref',
    'production_date',
    'status',
  ],
  purchase_order: [
    'po_id',
    'po_ref',
    'sku_group',
    'supplier_id',
    'destination',
    'issue_date',
    'status',
    'cargo_ready_date',
    'incoterms',
    'payment_terms',
    'ship_to_address',
    'created_at',
    'created_by',
    'notes',
    'total_units',
    'total_cartons',
    'total_pallets',
    'total_weight_lb',
    'total_volume_cbm',
    'product_subtotal',
    'mfg_start_date',
    'mfg_expected_completion',
    'packaging_notes',
    'inbound_cost',
    'storage_cost',
    'supplier_credit_debit',
    'landed_total',
    'rfq_pdf_url',
    'inventory_summary_url',
    'po_pdf_url',
    'shipping_marks_url',
    'signed_pi_url',
    'box_artwork_url',
    'mfg_shipping_marks_url',
  ],
  po_ci: ['po_id', 'sku_id', 'ci_id', 'qty_on_shipment'],
  commercial_invoice: [
    'ci_id',
    'ci_ref',
    'house_bl',
    'master_bl',
    'vessel',
    'voyage',
    'port_of_loading',
    'port_of_discharge',
    'etd',
    'eta',
    'total_qty',
    'packing_list_ref',
    'freight_cost_usd',
    'status',
    'ci_doc_url',
    'bl_doc_url',
    'packing_list_doc_url',
  ],
  ci_allocation: [
    'ci_id',
    'po_id',
    'sku_id',
    'warehouse_id',
    'qty_allocated',
    'allocated_by',
    'allocated_at',
  ],
  grn: [
    'grn_id',
    'grn_ref',
    'ci_id',
    'po_id',
    'sku_id',
    'warehouse_id',
    'receive_type',
    'import_entry_number',
    'customs_cleared_date',
    'received_date',
    'discrepancy_notes',
    'total_received',
    'status',
    'grn_doc_url',
    'customs_clearance_url',
    'cube_master_url',
    'freight_receipt_url',
    'transaction_cert_url',
  ],
  grn_line_item: [
    'line_id',
    'grn_id',
    'po_id',
    'sku_id',
    'expected_qty',
    'received_qty',
    'damaged_qty',
    'delta',
    'status',
  ],
  discrepancy: ['disc_id', 'line_id', 'type', 'qty', 'notes', 'logged_at'],
} as const

export type ErdV9Entity = keyof typeof ERD_V9_ENTITY_COLUMNS

export const ERD_V9_ENTITIES: ErdV9Entity[] = Object.keys(ERD_V9_ENTITY_COLUMNS) as ErdV9Entity[]

export function isErdV9Entity(value: string): value is ErdV9Entity {
  return ERD_V9_ENTITIES.includes(value as ErdV9Entity)
}

export function parseErdV9Limit(raw: string | null, defaultLimit: number = 200): number {
  const candidate = raw === null ? defaultLimit : Number.parseInt(raw, 10)
  if (!Number.isFinite(candidate)) {
    return defaultLimit
  }
  if (candidate < 1) {
    return 1
  }
  if (candidate > 2000) {
    return 2000
  }
  return candidate
}
